import type { ComponentType } from "react";
import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconBold,
  IconBox,
  IconBrandGithub,
  IconBrandTwitter,
  IconBrightness,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCommand,
  IconCreditCard,
  IconCrown,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypeDoc,
  IconFileTypePdf,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconRosetteDiscountCheck,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUsers,
  IconUserX,
  IconVideo,
  IconX,
} from "@tabler/icons-react";

export type Icon = ComponentType<IconProps>;

export const Icons = {
  logo: IconStack2,
  close: IconX,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronDown: IconChevronDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsDown: IconChevronsDown,
  check: IconCheck,
  checks: IconChecks,
  circle: IconCircle,
  circleCheck: IconCircleCheck,
  circlePlus: IconCirclePlus,
  circleX: IconCircleX,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  edit: IconEdit,
  add: IconPlus,
  minus: IconMinus,
  upload: IconUpload,
  share: IconShare,
  externalLink: IconExternalLink,
  info: IconInfoCircle,
  warning: IconAlertTriangle,
  alert: IconAlertCircle,
  dashboard: IconLayoutDashboard,
  product: IconBox,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,
  user: IconUser,
  users: IconUsers,
  profile: IconUserCircle,
  userEdit: IconUserEdit,
  userX: IconUserX,
  teams: IconUsers,
  billing: IconCreditCard,
  pro: IconCrown,
  workspace: IconStack2,
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  page: IconFile,
  post: IconFileText,
  media: IconPhoto,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  folder: IconFolder,
  login: IconLogin,
  logout: IconLogout,
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,
  trendingUp: IconTrendingUp,
  trendingDown: IconTrendingDown,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,
  command: IconCommand,
  code: IconCode,
  clock: IconClock,
  clipboard: IconClipboardText,
  dots: IconDots,
  moreHorizontal: IconDots,
  xCircle: IconCircleX,
  plusCircle: IconCirclePlus,
  calendar: IconCalendar,
  alertCircle: IconAlertCircle,
  gripVertical: IconGripVertical,
  ellipsis: IconDotsVertical,
  grip: IconGripVertical,
  help: IconHelpCircle,
  lock: IconLock,
  music: IconMusic,
  paperclip: IconPaperclip,
  pizza: IconPizza,
  rosette: IconRosetteDiscountCheck,
  selector: IconSelector,
  chevronsUpDown: IconSelector,
  slash: IconSlash,
  sparkles: IconSparkles,
  star: IconStar,
  arrowRight: IconArrowRight,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
} as const;
